### ISSUE TITLE
Shortcuts, Win10 issues

### ISSUE THREAD

**Issue by DRYN07** [martin-stone/touchcursor#14]
Dear Martin,

Since there is no way to message you, I can only write here. I use TouchCursor for years, one of the best little stuff in my life. However it lacks some features and have some issues on windows 10 so it would be awesome if you could come back to develop it further :) 

- the exe whitelist/blacklist does not work on win10
- there are no configurable shortcuts (for example to enable/disable the software)

**Comment by martin-stone** [comment]
Thanks for the bug report. I'm not sure when it will get addressed -- TC has been meeting my needs for the last 15 years, so it's not high priority for me. Pull requests are welcome, though.

**Comment by manfred-exz** [comment]
@DRYN07 Try this version, I recompiled it with latest visual studio. The whitelist problem is solved.
[TouchCursor.zip](https://github.com/martin-stone/touchcursor/files/5644111/TouchCursor.zip)

**Comment by martin-stone** [comment]
@manfred-exz, did you need to make any code changes, or was compiling with latest tools all that it needed?

**Comment by manfred-exz** [comment]
> @manfred-exz, did you need to make any code changes, or was compiling with latest tools all that it needed?

No code change at all. Build in 64bit should solve the problem.
BTW, I was using boost 1.74.0 & wxMSW 2.8.12.

**Comment by DRYN07** [comment]
Works like a charm, thank you very much

**Comment by bubbavox** [comment]
Thanks very much!

**Comment by WTanardi** [comment]
> No code change at all. Build in 64bit should solve the problem.

I'm sorry I don't understand, how do I build it in 64bit?

I've tried downloading the version sent here,

> @DRYN07 Try this version, I recompiled it with latest visual studio. The whitelist problem is solved. [TouchCursor.zip](https://github.com/martin-stone/touchcursor/files/5644111/TouchCursor.zip)

but it still doesn't work, see below as I tried to whitelist chrome and other programs

![image](https://github.com/martin-stone/touchcursor/assets/90451337/ec16ad71-35ea-4437-90e4-5806ac580531)

**Comment by DRYN07** [comment]
It should be like:  photoshop.exe; illustrator.exe; etc...

I am on latest Win11 and it works fine :/

However you should check out this for an alternative:

[https://github.com/petoncle/mousemaster](https://github.com/petoncle/mousemaster)
